buildscript {
    repositories {
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven { url = 'https://maven.neoforged.net/releases' }
    }
    dependencies {
        classpath 'net.neoforged.gradle:userdev:7.1.38'
    }
}

apply plugin: 'java-library'
apply plugin: 'maven-publish'
apply plugin: 'net.neoforged.gradle.userdev'

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')
    exclude("**/*.bbmodel")
    exclude("src/generated/**/.cache")
}

repositories {
    maven { url = 'https://maven.aliyun.com/repository/public' }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        workingDirectory project.file('run')
        systemProperty 'forge.logging.console.level', 'info'
        programArguments '--username', 'Dev', '--uuid', '00000000-0000-0000-0000-000000000000'
    }

    server {
        workingDirectory project.file('run/server')
        systemProperty 'forge.logging.console.level', 'info'
    }

    data {
        workingDirectory project.file('run')
        programArguments '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : mod_id,
            'Specification-Vendor'    : 'colorblocks',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : 'colorblocks',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}
