org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.86
neo_version_range=[21.1.86,)
loader_version_range=[4,)

mod_id=colorblocks
mod_name=Color Blocks
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.colorblocks
